
const productos = [
    { codigo: "116", descripcion: "Agua Villa Manaos 6x2L", categoria: "manaos", imagen: "../assets/aguaManaos2L.png", precio: "$2300" },
    { codigo: "125", descripcion: "Bidon MANAOS x 6lts", categoria: "manaos", imagen: "../assets/aguaManaos6L.png", precio: "$1.090" },
    { codigo: "117", descripcion: "Agua Villa Manaos 12x500", categoria: "manaos", imagen: "../assets/AguaManaos500.webp", precio: "$3.000" },
    { codigo: "115", descripcion: "GASIFICADA Manaos 12x500cc", categoria: "manaos", imagen: "../assets/AguaManaos500.webp", precio: "$3.000" },
    { codigo: "1005", descripcion: "LEVITE POMELO //6x2.25//", categoria: "Villa del sur", imagen: "../assets/LEVITEPOMELO2.25.webp", precio: "$5.000" },
    { codigo: "290", descripcion: "AGUA CIMES 6x600 cc", categoria: "Villa del sur", imagen: "../assets/AGUACIMES600.webp", precio: "$1.400" },
    { codigo: "292", descripcion: "VILLAVICENCIO 6x1,5", categoria: "Villa del sur", imagen: "../assets/VILLAVICENCIO15.png", precio: "$3.200" },
    { codigo: "345", descripcion: "VILLAVICENCIO 6x2lts", categoria: "Villa del sur", imagen: "../assets/VILLAVICENCIO2L.webp", precio: "$3500" },
    { codigo: "1062", descripcion: "FRESH MANZANA 6x1,5", categoria: "baggio", precio: "$3.500.00", imagen: "../assets/freshmanzana15.jpg" },
    { codigo: "1060", descripcion: "FRESH NARANJA 6x1,5", categoria: "baggio", precio: "$3.500.00", imagen: "../assets/freshnaranja15.jpg" },
    { codigo: "1063", descripcion: "FRESH PERA 6x1,5L", categoria: "baggio", precio: "$3.500.00", imagen: "../assets/freshpera15.jpg" },
    { codigo: "1061", descripcion: "FRESH POMELO 6x1,5", categoria: "baggio", precio: "$3.500.00", imagen: "../assets/freshpomelo15.webp" },
    { codigo: "160", descripcion: "PLACER MANZANA 6X1,5", categoria: "manaos", precio: "$4.100.00", imagen: "../assets/PLACERMANZANA15.jpg" },
    { codigo: "157", descripcion: "PLACER NARANJA 6x1,5", categoria: "manaos", precio: "$4.100.00", imagen: "../assets/PLACERNARANJA15.jpg" },
    { codigo: "161", descripcion: "PLACER POMELO 6x1,5", categoria: "manaos", precio: "$4.100.00", imagen: "../assets/PLACERPOMELO15.JPG" },
    { codigo: "164", descripcion: "Placer pomelo 12x500", categoria: "manaos", precio: "$4.000.00", imagen: "../assets/PLACERPOMELO500.jpg" },
    { codigo: "130", descripcion: "SABORIZADA BRIO MANZANA 6x1.5lt", categoria: "Villa del sur", precio: "$1.900.00", imagen: "../assets/BRIOMANZANA15.jpg" },
    { codigo: "128", descripcion: "SABORIZADA BRIO NARANJA 6x1,5lt", categoria: "Villa del sur", precio: "$1.900.00", imagen: "../assets/BRIONARANJA15.jpg" },
    { codigo: "127", descripcion: "SABORIZADA BRIO POMELO 6x1.5lt", categoria: "Villa del sur", precio: "$1.900.00", imagen: "../assets/BRIOPOMELO15.jpg" },
    { codigo: "282", descripcion: "VILLA Del SUR MANZANA 6x1,5", categoria: "Villa del sur", precio: "$5.000.00", imagen: "../assets/VILLADelSURMANZANA15.webp" },
    { codigo: "283", descripcion: "VILLA Del SUR PERA 6x1,5", categoria: "Villa del sur", precio: "$5.000.00", imagen: "../assets/VILLADelPERA15.WEBP" },
    { codigo: "124", descripcion: "CIMES Saborizada PERA 6x600", categoria: "Villa del sur", precio: "$2.000.00", imagen: "../assets/CIMESPERA600.jpg" },
    { codigo: "121", descripcion: "CIMES Saborizada POMELO 6x600", categoria: "Villa del sur", precio: "$2.000.00", imagen: "../assets/CIMESPOMELO600.jpg" },
    { codigo: "287", descripcion: "Levite Manzana 12x500", categoria: "Villa del sur", precio: "$5.500.00", imagen: "../assets/LeviteManzana500.webp" },
    { codigo: "286", descripcion: "Levite Naranja 12x500", categoria: "Villa del sur", precio: "$5.500.00", imagen: "../assets/Levitenaranja500.webp" },
    { codigo: "288", descripcion: "Levite Pera 12x500", categoria: "Villa del sur", precio: "$5.500.00", imagen: "../assets/Levitepera500.webp" },
];

export default productos;